app:
  volumes:
    - ./:/var/www/bunny/
  build: ./
  environment:
    REDIS_URL: redis://redis:6379
    MAX_THREADS: 10
  links:
    - redis
  ports:
    - '5000:5000'
  command: foreman start
redis:
  image: redis
  ports:
    - '6379:6379'
